### ISSUE TITLE
Client application gets stuck even after the delegate method is done

### ISSUE THREAD

**Issue by thilux** [simon-engledew/sshim#12]
Hello,

I have the following server implementation using sshim:

```
import sshim

def process_connection(script):
    script.write('password: ')
    script.expect(re.compile('(?P<password>.*)')).groupdict()
    script.writeline('You are connected')

server = sshim.Server(process_connection, port=1234)

if __name__ == '__main__':
    try:
        server.start()
    except KeyboardInterrupt:
        server.stop()
    
```

When I connect to it, the initial prompt works fine:

```
$> ssh test@localhost -p 1234
password: 
You are connected
```

But the client get's stuck at 'You are connected' endlessly, even if server.stop() is executed (key board interrupting the server). The expected was that if there was nothing more on the delegate function, that it would terminate the client's connection.

Would you kindly take a look at this?

Thank you!

**Comment by simon-engledew** [comment]
Well spotted! This commit should fix it:

https://github.com/simon-engledew/sshim/commit/1d8d20a3013297fbc9c7540a0b64dd0986b1588a

**Comment by thilux** [comment]
Hey Simon,

I see this change has not made into the latest pypi version of sshim. Do you have plans to release a new version and make sure this change is included?

Thank you!

**Comment by simon-engledew** [comment]
I've just pushed 1.3.2. Let me know if it fixes your issue!

**Comment by thilux** [comment]
Hi @simon-engledew , yes, my issue is now fixed! I think you can close this report then.

Thanks a lot!
