### ISSUE TITLE
Please state what your license is for this code.

### ISSUE THREAD

**Issue by dahvid** [simon-engledew/sshim#14]
Txs!

**Comment by simon-engledew** [comment]
The project has been around for 8 years and I think you are the first person who has ever asked. 🤔 
What are you using it for?! 😄

**Comment by dahvid** [comment]
An in-house prototype at GE. If it went into production it'd be rewritten
in another language. BTW you're listed as MIT license through
pip-licenses.  Thanks for the easy-to-use package.
Regards,
David

**Comment by simon-engledew** [comment]
Cool! Thanks for letting me know. :) I was thinking about writing a successor to sshim in Golang or Rust to do some CV padding, it's nice to know that somehow people find (and use) it!

I'll stick an MIT licence in the repo too. 👍

**Comment by simon-engledew** [comment]
I've thrown together a prototype successor for SSHim that uses Starlark instead of Python.

https://github.com/simon-engledew/mock-ssh-server/
